### ISSUE TITLE
`gen2-spi`/`device-yolo-parsing` running error

### ISSUE THREAD

**Issue by 759401524** [luxonis/esp32-spi-message-demo#13]
I ran the [device-yolo-parsing](https://github.com/luxonis/depthai-experiments/tree/master/gen2-spi/device-yolo-parsing) demo on [OAK-D-IOT-40
](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM1092.html) use the default blob [tiny-yolo-v3.blob.sh4cmx4NCE1](https://github.com/luxonis/depthai-experiments/blob/master/gen2-spi/device-yolo-parsing/tiny-yolo-v3.blob.sh4cmx4NCE1), The code runs normally, and the esp32 output is normal through the serial debugging tool.

But using other models, such as the model [here](https://github.com/luxonis/depthai-python/blob/main/examples/models/tiny-yolo/model.yml), it only runs normally for 1-2 seconds and the esp32 output displays `Timeout: no response from remote device...
failed to recv packet`

Is there any special requirements for the `yolo` model when converting to a blob ?

depthai  version

```
Name: depthai
Version: 2.12.0.0
Summary: DepthAI Python Library
Home-page: https://github.com/luxonis/depthai-python
Author: Luxonis
Author-email: support@luxonis.com
License: MIT
Location: /home/mulong/mambaforge/envs/depthai/lib/python3.10/site-packages
Requires: 
Required-by: depthai-sdk

```

**Comment by themarpe** [comment]
Main discussion moved to:
https://github.com/luxonis/depthai-experiments/issues/247
