### ISSUE TITLE
Build error: GPIO_PIN_INTR_NEGEDGE undeclared 

### ISSUE THREAD

**Issue by bhavers** [luxonis/esp32-spi-message-demo#15]
When i run ```idf.py build``` for  jpeg_webserver_demo,  i get the following error:

```
user1@machine:/esp/esp32-spi-message-demo/components/depthai-spi-api/common/esp32_spi_impl.c:73:20: error: 'GPIO_PIN_INTR_NEGEDGE' undeclared (first use in this function); did you mean 'GPIO_INTR_NEGEDGE'?
         .intr_type=GPIO_PIN_INTR_NEGEDGE,
                    ^~~~~~~~~~~~~~~~~~~~~
                    GPIO_INTR_NEGEDGE
```

Is this a problem in the code, or do i need to do some additional configuration (i have ran ```idf.py menuconfig``` and entered the wifi ssid and password).

**Comment by themarpe** [comment]
Hi @bhavers 

Might be an updated esp idf tooling - check the version, we build against: `v4.1`

**Comment by bhavers** [comment]
Ah, that might be it. Will figure out how to downgrade later this evening and let you know the outcome.
```
idf.py --version
ESP-IDF v5.0-dev-1426-ge899edd793
```

**Comment by bhavers** [comment]
Thanks, this solved it. My be worth mentioning in Getting started that the standard process does not activate the right branch. 
For others that have had the same problem, see instruction to choose v4.1 branch: https://docs.espressif.com/projects/esp-idf/en/v4.1/versions.html#updating-release-branch
Don't forget to reset environment (restart Terminal) and re-do ./install.sh esp32.

**Comment by themarpe** [comment]
CC: @Erol444 do you mind covering this point (in docs as well as in README of this repo)
