### ISSUE TITLE
Build error when running mjpeg-streaming-wifi

### ISSUE THREAD

**Issue by KevinMano** [luxonis/esp32-spi-message-demo#16]
Hello, I'm trying to run the "mjpeg-streaming-wifi" demo with the OAK-D-IOT 75. I'm using the ESP-IDF extension in Visual Studio Code. When I click the build project button in the extension, I receive the following error message in the terminal. 

<img width="614" alt="image" src="https://user-images.githubusercontent.com/25656580/153314253-e8934950-fdac-4aa0-92e2-2f0a1077fb05.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/25656580/153314704-1fe040c6-4997-41b7-9224-bb16717c8cb8.png">

<img width="601" alt="image" src="https://user-images.githubusercontent.com/25656580/153314759-a9c0290a-5671-4fcf-ac9c-6239b5c71e13.png">

It also records these problems in the 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/25656580/153314848-65bf9449-17c9-4ab6-9b46-09cf1491a26f.png">

Any tips on how I can resolve this? I'm unsure if this is a workspace setup problem or actually something in the files.

**Comment by themarpe** [comment]
@KevinMano 
I think it might be related to tooling version as in #15 

> Might be an updated esp idf tooling - check the version, we build against: v4.1

Also try compiling from command line first:
```
cd [project]
idf.py build
```

**Comment by KevinMano** [comment]
Hi @themarpe, thank you. I did a full clean and reinstall of the tools, that allowed me to build and flash the project. 
I'm still getting an error when I run the "main.py" code, it just shows the following in the ESP-IDF monitor.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/25656580/153653813-e86f1767-003a-468b-9b35-9aaad04f7d4c.png">

And the URI doesn't exist when I try to view the webpage.

**Comment by themarpe** [comment]
@KevinMano 
Have you ran the corresponding DepthAI code? Also, try navigating to `/` instead of `/getframe` - I might've refactored the URLs without fixing up the README.md...

**Comment by KevinMano** [comment]
I did run the corresponding depthAI code in another window. The main.py example.

I tried the different URL you mentioned, and I get this blank screen in the URL.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/25656580/153665650-d952672e-4e31-434d-bccc-823b1ea93bca.png">

In the monitor, I get this.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/25656580/153665718-273d4fe5-715f-4804-bbe5-582c993f5cc8.png">

Which tells me images are sending, but either go somewhere else, or could it be a browser issue (I'm running this on Google Chrome)? 

The other window where I'm running the python DepthAI code shows this. 
<img width="921" alt="image" src="https://user-images.githubusercontent.com/25656580/153665859-261a78eb-2eba-4380-b53c-1b2f91c7e2be.png">

**Comment by themarpe** [comment]
@KevinMano 
Maybe try a different browser, just for a test (Firefox / Chrome on a phone / ...)
Also, make sure to first start esp32 and then depthai afterwards - looks okay as is right now, but for next time.

Also, did you install the requirements listed in the project folder?

(Note: for text, prefer posting it in code blocks compared to screenshots, as its searchable and easier to view on different kinds of devices)

**Comment by KevinMano** [comment]
Thank you so much, I tested it with Edge and it works. Thank you again.
