### ISSUE TITLE
 Failed to resolve component 'depthai-spi-api'.

### ISSUE THREAD

**Issue by vipulkumar-developer** [luxonis/esp32-spi-message-demo#18]
Hi, I'm trying to run the examples of the repository but when I try to use the command idf.py menuconfig it gives me this error " Failed to resolve component 'depthai-spi-api'.".

How can I fix it?

**Comment by themarpe** [comment]
Hi @vipulkumar-developer 
Have you initialized the submodules as well?

 Run the following: `git submodule update --init --recursive` in the root of the repository folder

**Comment by vipulkumar-developer** [comment]
Ok, thank you very much.
