### ISSUE TITLE
Raw IMU Data metadata parsing fails

### ISSUE THREAD

**Issue by elblogbruno** [luxonis/esp32-spi-message-demo#19]
Hi,
I am trying to parse IMU raw data from the IMU node on my oak d lite and it is failing.

```
print("Creating IMU node...")
imu = pipeline.create(dai.node.IMU)
imu.enableIMUSensor([dai.IMUSensor.ARVR_STABILIZED_GAME_ROTATION_VECTOR], 400)
# above this threshold packets will be sent in batch of X, if the host is not blocked and USB bandwidth is available
imu.setBatchReportThreshold(1)
# maximum number of IMU packets in a batch, if it's reached device will block sending until host can receive it
# if lower or equal to batchReportThreshold then the sending is always blocking on device
# useful to reduce device's CPU load  and number of lost packets, if CPU load is high on device side due to multiple nodes
imu.setMaxBatchReports(10)


spiOut1 = pipeline.create(dai.node.SPIOut)
spiOut1.setStreamName("spiimuout")
spiOut1.setBusId(0)
spiOut1.input.setBlocking(False)
spiOut1.input.setQueueSize(2)

# Link plugins IMU -> XLINK
imu.out.link(spiOut1.input)
```

```
dai::RawIMUData imu_data;

    if(mySpiApi.parse_metadata(&imu_msg.raw_meta, imu_data)){
        ESP_LOGI(TAG, "Metadata parsed successfully\n");
    }
    else{
        ESP_LOGI(TAG, "Metadata parsing failed\n");
    }
```

I am receiving data as if I print data:
```
if (mySpiApi.req_message(&imu_msg, SPI_IMU_OUT)) {
       ESP_LOGI(TAG, "Received imu data from camera: %s\n", imu_msg.raw_meta.data);
```

I read this:
`��packets���acceleroMeter��accuracy`

Thanks
Cordially,

**Comment by themarpe** [comment]
Hi @elblogbruno 
Check out the parse_message function - that'll properly deserialize the message.

**Comment by elblogbruno** [comment]
Hi @themarpe 
Just tried it and it is still not working. I have also seen 'parse_metadata' calls 'parse_message'.

**Comment by themarpe** [comment]
@elblogbruno 
What is the output now? Same?

Make sure your depthai library matches `depthai-shared`

**Comment by elblogbruno** [comment]
Yes exactly the same. 
I am at the latest commit from the main repo

**Comment by elblogbruno** [comment]
ouh one second I have depthai 2.13.0.0 installed. Let me update

**Comment by elblogbruno** [comment]
Still the same

**Comment by themarpe** [comment]
~~Can you post full log with `DEPTHAI_LEVEL=debug` as well as the output of esp32?~~

@elblogbruno 
After the `parse_metadata` call, the "Raw"Message is created. Use it in similar manner as on host side:

eg:
`imu_data.packets[0].gyroscope`

**Comment by themarpe** [comment]
@elblogbruno 
After the `parse_metadata` call, the "Raw"Message is created. Use it in similar manner as on host side:

eg:
`imu_data.packets[0].gyroscope`

**Comment by elblogbruno** [comment]
https://pastebin.com/8S9QhC5z camera log. I am not getting any interesting feedback maybe I am doing it wrong.

And this is the ESP32 https://pastebin.com/JXZbykZR

I did follow https://docs.luxonis.com/projects/api/en/latest/tutorials/debugging/ but all I am getting are warning and info level messages.

**Comment by elblogbruno** [comment]
> eg:
> `imu_data.packets[0].gyroscope`

Sure i am iterating the packets and reading  them

`for(const auto& imu_data : imu_data.packets){
        imu_data.rotationVector.i
    }`

**Comment by elblogbruno** [comment]
i have tried the imu demo python code and i can read values from the sensor so it is not a problem of him

**Comment by themarpe** [comment]
@elblogbruno 

Sorry if I'm misunderstanding here - what seems to be the root issue? Are the values in the IMUPackets you are iterating over and printing not correct? 

Or are you refering to this:

> I am receiving data as if I print data:\

> if (mySpiApi.req_message(&imu_msg, SPI_IMU_OUT)) {
       ESP_LOGI(TAG, "Received imu data from camera: %s\n", imu_msg.raw_meta.data);

> I read this:
��packets���acceleroMeter��accuracy

If so, printing the data out that way isn't supposed to be user readable in any meaningful way.

**Comment by elblogbruno** [comment]
Sorry if I did misunderstand you.

The main problem is that `parse_metadata ` is not parsing metadata. (If I try read packets[0] for example no packets are there)

The part of printing data was just to prove I was receiving data.

**Comment by themarpe** [comment]
@elblogbruno 
Can you simultaneously send the data to the host as well and see what you receive there?

Also what is the size of the data that you are printing?

By the looks of it, there is actually no packets...

**Comment by elblogbruno** [comment]
> Also what is the size of the data that you are printing?

138 is the size

> Can you simultaneously send the data to the host as well and see what you receive there?

Just did so, and I am having data received on the host.

![image](https://user-images.githubusercontent.com/10481058/160011290-f1f95f67-4d68-4f69-a087-e5c3b62e2fb9.png)

**Comment by themarpe** [comment]
@elblogbruno 
Can you post all the 138B as hex here? Wondering if its transmitted correctly and not correctly parsed or the other way around

**Comment by elblogbruno** [comment]
This is an example:

```
I (21816) ESP32_SPI_IMPL: Size: 138


b901ba01b904b9078800000000880000000088000000000000b9020000b9020000b9078800000000880000000088000000000000b9020000b9020000b9078800000000880000000088000000000000b9
020000b9020000b909880000cc3b880000ac3b88000000008800fc7f3f880000000085c60003b902860af80700867d3af009b9023986789ef82c
```

**Comment by themarpe** [comment]
@elblogbruno 

```
i: 0.006226, j: 0.005249, k: 0.000000, real: 0.999939
```

Got this data out of the 138B

So the serialization is mismatched.

Please double check your:
 - depthai-python library version
 - depthai-shared commit version.

Make sure both are the same (best bet is to go to 2.15.1.0 & 2.15.1 for python & shared respectively)

If it still doesn't work, post a complete MRE and preferably logs with `DEPTHAI_LEVEL=debug` env var set

**Comment by elblogbruno** [comment]
> best bet is to go to 2.15.1.0 & 2.15.1 for python & shared respectively

You were right. Problem fixed! Thanks!

One thing before closing the issue. Before I had to modify the pins on the oak d lite chip to put it in standalone mode, now I have done that and it is not booting the flashed pipeline. Is it because it is not needed to modify the pins?

By pins I mean this:

![image](https://user-images.githubusercontent.com/10481058/160475055-ff085e6f-a48a-48e5-80ee-ab3f306ac216.png)

Sorry for bothering you with lot of issues recently 😆

**Comment by themarpe** [comment]
@elblogbruno 

> You were right. Problem fixed! Thanks!

Glad to hear it got resolved :) 

> Before I had to modify the pins on the oak d lite chip to put it in standalone mode, now I have done that and it is not booting the flashed pipeline. Is it because it is not needed to modify the pins?

You'll have to set these back to 0x3 (that'd be 000011 looking in same direction as the above picture)

We'll be improving the docs on the standalone mode in the upcoming days (CC: @Erol444 )

**Comment by elblogbruno** [comment]
> You'll have to set these back to 0x3 (that'd be 000011 looking in same direction as the above picture)

Ok Thanks. The current setup in the picture is the original form the oak came in. 
I will try your idea.



> We'll be improving the docs on the standalone mode in the upcoming days (CC: @Erol444 )

Can't wait! :)

**Comment by elblogbruno** [comment]
> We'll be improving the docs on the standalone mode in the upcoming days (CC: @Erol444 )

Just wondering if they are updated, sorry for opening the issue again.
Thanks
Bruno
